spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-basic-learn-spring-batch?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
  batch:
    initialize-schema: always